DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    ok VARCHAR(255),
    SourceIP FLOAT(64),
    DestinationIP FLOAT(64), 
    SourcePort INT(64),
    DestinationPort INT(64), 
    Duration FLOAT(64), 
    FlowBytesSent FLOAT(64), 
    FlowSentRate FLOAT(64), 
    FlowBytesReceived FLOAT(64), 
    FlowReceivedRate FLOAT(64),
    PacketLengthVariance FLOAT(64), 
    PacketLengthStandardDeviation FLOAT(64), 
    PacketLengthMean FLOAT(64), 
    PacketLengthMedian FLOAT(64), 
    PacketLengthMode FLOAT(64), 
    PacketLengthSkewFromMedian FLOAT(64),
    PacketLengthSkewFromMode FLOAT(64), 
    PacketLengthCoefficientofVariation FLOAT(64), 
    PacketTimeVariance FLOAT(64), 
    PacketTimeStandardDeviation FLOAT(64), 
    PacketTimeMean FLOAT(64), 
    PacketTimeMedian FLOAT(64),
    PacketTimeMode FLOAT(64), 
    PacketTimeSkewFromMedian FLOAT(64), 
    PacketTimeSkewFromMode FLOAT(64), 
    PacketTimeCoefficientofVariation FLOAT(64), 
    ResponseTimeTimeVariance FLOAT(64), 
    ResponseTimeTimeStandardDeviation FLOAT(64),
    ResponseTimeTimeMean FLOAT(64), 
    ResponseTimeTimeMedian FLOAT(64), 
    ResponseTimeTimeMode FLOAT(64), 
    ResponseTimeTimeSkewFromMedian FLOAT(64), 
    ResponseTimeTimeSkewFromMode FLOAT(64), 
    ResponseTimeTimeCoefficientofVariation FLOAT(64),
    pred_DTC_DoH int(1),
    pred_RFC_DoH int(1),
    pred_XGB_DoH int(1),
    pred_KNN_DoH int(1),
    pred_GNB_DoH int(1),
    pred_CNN_1D_Intrusion int(1),
    pred_CNN_2D_Intrusion int(1),
    Label_DoH VARCHAR(255),
    Nb_model_DoH VARCHAR(255),
    Label_Intrusion VARCHAR(255),
    Nb_model_Intrusion VARCHAR(255)

);